name: Deploy Frontend Manually

on:
  push:
    branches:
      - main
  workflow_dispatch: # This enables manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          CI: false

      - name: Install git-ftp
        run: sudo apt-get install git-ftp

      - name: Deploy to FTP
        run: |
          git config git-ftp.url "ftp://${{ secrets.FTP_SERVER }}"
          git config git-ftp.user "${{ secrets.FTP_USERNAME }}"
          git config git-ftp.password "${{ secrets.FTP_PASSWORD }}"
          git ftp init --force --remote-root "/snippets.zioan.com" ./build
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
